# Form implementation generated from reading ui file 'homedashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listObject = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listObject.setGeometry(QtCore.QRect(240, 130, 471, 391))
        self.listObject.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listObject.setObjectName("listObject")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(250, 60, 113, 32))
        self.pushButton_add.setStyleSheet("background-color: rgb(0, 134, 0);\n"
"color:white;")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_edit.setGeometry(QtCore.QRect(420, 60, 113, 32))
        self.pushButton_edit.setStyleSheet("background-color: rgb(0, 134, 0);\n"
"color:white;")
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(590, 60, 113, 32))
        self.pushButton_delete.setStyleSheet("background-color: rgb(0, 134, 0);\n"
"color:white;")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 101, 551))
        self.widget.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.widget.setStyleSheet("background-color: rgb(0, 67, 9);\n"
"boorder-radius:10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setMaximumSize(QtCore.QSize(200, 1000))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_3.setMaximumSize(QtCore.QSize(60, 60))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/cropped_image.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.widget_4)
        self.pushButton_home = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_home.setFont(font)
        self.pushButton_home.setStyleSheet("\n"
"background-color: transparent;\n"
"color:black;\n"
"\n"
"")
        self.pushButton_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/home-2.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.pushButton_home.setIcon(icon)
        self.pushButton_home.setIconSize(QtCore.QSize(29, 29))
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout.addWidget(self.pushButton_home)
        self.pushButton_search = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setStyleSheet("\n"
"background-color: transparent;\n"
"color:black;\n"
"\n"
"")
        self.pushButton_search.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/search-interface-symbol.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.pushButton_search.setIcon(icon1)
        self.pushButton_search.setIconSize(QtCore.QSize(29, 29))
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout.addWidget(self.pushButton_search)
        self.pushButton_setting = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setting.setFont(font)
        self.pushButton_setting.setStyleSheet("\n"
"background-color: transparent;\n"
"color:black;\n"
"\n"
"")
        self.pushButton_setting.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/settings.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.pushButton_setting.setIcon(icon2)
        self.pushButton_setting.setIconSize(QtCore.QSize(29, 29))
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.verticalLayout.addWidget(self.pushButton_setting)
        self.pushButton_game = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_game.setFont(font)
        self.pushButton_game.setStyleSheet("\n"
"background-color: transparent;\n"
"color:black;\n"
"\n"
"")
        self.pushButton_game.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/bar-chart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_game.setIcon(icon3)
        self.pushButton_game.setIconSize(QtCore.QSize(29, 29))
        self.pushButton_game.setObjectName("pushButton_game")
        self.verticalLayout.addWidget(self.pushButton_game)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout.addWidget(self.widget_5)
        self.txt_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_search.setGeometry(QtCore.QRect(250, 20, 421, 21))
        self.txt_search.setObjectName("txt_search")
        self.btn_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(120, 20, 113, 32))
        self.btn_search.setStyleSheet("color:white;")
        self.btn_search.setObjectName("btn_search")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add.setText(_translate("MainWindow", "ADD"))
        self.pushButton_edit.setText(_translate("MainWindow", "EDit"))
        self.pushButton_delete.setText(_translate("MainWindow", "delete"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
